const actionTypes = {
  SHOW_GENERAL_NOTIFICATION: "SHOW_GENERAL_NOTIFICATION",
  CLOSE_GENERAL_NOTIFICATION: "CLOSE_GENERAL_NOTIFICATION",
  ADD_PURCHASE: "ADD_PURCHASE"
};

export const {
  ADD_PURCHASE,
  SHOW_GENERAL_NOTIFICATION,
  CLOSE_GENERAL_NOTIFICATION
} = actionTypes;
